PRODUCTS = [

    {
        "product_id": 1,
        "product_name": "Sona Masoori Rice 5kg",
        "category": "Rice & Grains",
        "unit_price": 350,
        "base_demand": 15,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 2,
        "product_name": "Basmati Rice 5kg",
        "category": "Rice & Grains",
        "unit_price": 550,
        "base_demand": 10,
        "trend": +0.4,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 3,
        "product_name": "Wheat Flour (Atta) 5kg",
        "category": "Rice & Grains",
        "unit_price": 250,
        "base_demand": 12,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 4,
        "product_name": "Toor Dal 1kg",
        "category": "Pulses & Lentils",
        "unit_price": 140,
        "base_demand": 8,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 5,
        "product_name": "Moong Dal 1kg",
        "category": "Pulses & Lentils",
        "unit_price": 130,
        "base_demand": 7,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 6,
        "product_name": "Rajma (Kidney Beans) 1kg",
        "category": "Pulses & Lentils",
        "unit_price": 160,
        "base_demand": 3,
        "trend": 0.0,
        "seasonal_months": [12, 1],
        "seasonal_multiplier": 3.0,
        "noise_range": (0.85, 1.15),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 7,
        "product_name": "Turmeric Powder 200g",
        "category": "Masalas & Spices",
        "unit_price": 60,
        "base_demand": 5,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 8,
        "product_name": "Garam Masala 100g",
        "category": "Masalas & Spices",
        "unit_price": 80,
        "base_demand": 3,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.4, 1.6),
        "zero_order_prob": 0.2,
    },

    {
        "product_id": 9,
        "product_name": "Biryani Masala 100g",
        "category": "Masalas & Spices",
        "unit_price": 100,
        "base_demand": 3,
        "trend": 0.0,
        "seasonal_months": [10, 11],
        "seasonal_multiplier": 3.5,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 10,
        "product_name": "Almonds (Badam) 500g",
        "category": "Dry Fruits & Nuts",
        "unit_price": 450,
        "base_demand": 2,
        "trend": 0.0,
        "seasonal_months": [10, 11],
        "seasonal_multiplier": 3.5,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 11,
        "product_name": "Cashew Nuts (Kaju) 500g",
        "category": "Dry Fruits & Nuts",
        "unit_price": 550,
        "base_demand": 2,
        "trend": +0.5,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 12,
        "product_name": "Peanuts (Groundnut) 500g",
        "category": "Dry Fruits & Nuts",
        "unit_price": 90,
        "base_demand": 5,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 13,
        "product_name": "Sunflower Oil 1L",
        "category": "Cooking Oils & Ghee",
        "unit_price": 180,
        "base_demand": 10,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 14,
        "product_name": "Groundnut Oil 1L",
        "category": "Cooking Oils & Ghee",
        "unit_price": 220,
        "base_demand": 6,
        "trend": -0.3,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 15,
        "product_name": "Mustard Oil 1L",
        "category": "Cooking Oils & Ghee",
        "unit_price": 200,
        "base_demand": 5,
        "trend": +0.3,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 16,
        "product_name": "Pure Ghee 1L",
        "category": "Cooking Oils & Ghee",
        "unit_price": 600,
        "base_demand": 3,
        "trend": 0.0,
        "seasonal_months": [10, 11],
        "seasonal_multiplier": 3.5,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 17,
        "product_name": "Sugar 1kg",
        "category": "Sugar, Salt & Sweeteners",
        "unit_price": 45,
        "base_demand": 10,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 18,
        "product_name": "Jaggery (Bella/Gud) 1kg",
        "category": "Sugar, Salt & Sweeteners",
        "unit_price": 70,
        "base_demand": 4,
        "trend": 0.0,
        "seasonal_months": [12, 1],
        "seasonal_multiplier": 3.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 19,
        "product_name": "Iodized Salt 1kg",
        "category": "Sugar, Salt & Sweeteners",
        "unit_price": 25,
        "base_demand": 9,
        "trend": -0.2,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.9, 1.1),
        "zero_order_prob": 0.0,
    },

    {
        "product_id": 20,
        "product_name": "Rock Salt (Sendha Namak) 500g",
        "category": "Sugar, Salt & Sweeteners",
        "unit_price": 40,
        "base_demand": 2,
        "trend": 0.0,
        "seasonal_months": [],
        "seasonal_multiplier": 1.0,
        "noise_range": (0.4, 1.6),
        "zero_order_prob": 0.2,
    },

]